### ISSUE TITLE
Understanding KIPEs results

### ISSUE THREAD

**Issue by KristinaGagalova** [bpucker/KIPEs#1] opened 2021-12-15 00:26 UTC
Hi, 
First of all, thank you for putting all the information about flavonoids together and making such a useful pipeline.

I have some questions about the output.

First I am having this error message
```
ERROR: no information (conserved residues) available about gene: FLS
ERROR: no information (conserved regions) available about gene: FLS
```
1) Does that mean that I have candidates but they don't have conserved residues/regions as the FLS? - **see comment below**
2) In the final_pep_files directory, those are all the hits with the flavonoid enzymes. How should I interpret the results, are those all gene copies or should I check each of them (conserved regions, residues)?
3) what is in the SUMMARY.html? are those the best hits for each gene?
3) What strategy do you recommend for gene copies? 

Thank you in advance for the help
Cheers
Kristina

**Comment by KristinaGagalova** [comment] 2021-12-15 04:37
About 1) - the error message only occurs with the FlavonoidBioSynBaits_v1.0.tar.gz dataset.
Everything works well with the baits and residues datasets

**Comment by bpucker** [comment] 2021-12-15 08:03
Hi Kristina,

I am glad to read that you find KIPEs useful. Thank you very much for providing comments about your experience.

1) The issue that you mention is due to missing information in the input. No information about the conserved FLS residues seems to be provided. That would be the case if the --residue argument is not used or if there are mismatches between the reference sequence names in the FASTA file and the residue file. I just tried to reproduce the issue, but it works fine for me. Since it works with the latest data set for you, I assume we can close this issue. Do you agree?

2) The final_pep_files directory contains all good candidates. I thought it might be useful to have some similar sequences to comparison in most cases (e.g. as negative control for following experiments or outgroups in phylogenetic trees). Usually, you need to exclude some of them. This depends on your initial filter criteria. There is a summary file that shows you which sequences have which conserved residues and how similar they are to the bait sequences. If you are working with a very distant plant species that is not well represented in the bait sequences, you might find that some of the otherwise conserved residues are flexible.

3) Yes, this HTML file shows you the best hit for each gene or all perfect hits if more than one hit show all conserved residues. The SUMMARY.txt is the extended version that gives you some statistics about all good candidates.

4) I am not sure if I understand this question. Most plant species should have more than just one copy. I think _Arabidopsis thaliana_ is one of the exceptions with only one (functional) copy for each step in the pathway. It is likely that you find multiple copies. They might be expressed in different tissues, different developmental stages, or in response to specific environmental conditions. I am currently working on an extension of KIPEs that will allow you to find co-expressed modules of gene copies.

Cheers
Boas

**Comment by KristinaGagalova** [comment] 2021-12-15 16:40
Thank you Boas for the reply! I had more of a general research question, not much on the software itself

About 4): I am running KIPEs the proteins from the genome annotations. Sometimes I am not sure is those are actual gene copies or possibly other enzymes of the pathway. It may depend on the filtering criteria and I possibly need to make a careful check of conserved regions/domains. Just checking if you have any recommendations but I understand that all the species are different and may be more divergent

I have another question:
5) in the case of enzymes with high sequence similarity ie F3H/FLS/LDOX. Do you recommend giving higher importance to the residues rather than the overall identity?

**Comment by bpucker** [comment] 2021-12-15 23:47
4) It is not uncommon to have multiple copies in a species. Especially polyploid species should have multiple copies. If all conserved residues are present, I would assume that you have multiple functional copies. If just one or two are missing, it could be helpful to check that the annotation is correct. For example, if residues are missing due to a gap in the alignment, this could indicate a missing exon.
5) In almost all species you would expect to find at least one copy of each of them. This can be helpful when assessing the identity of candidates that are listed under multiple functions. It is not always possible to clearly assign sequences to just one category, because these enzymes are known for their promiscuity (e.g. https://doi.org/10.3389/fpls.2021.733762). Overall identity should be above 50-60% and you would expect to find all or almost all conserved residues. The overall sequence identity is lower if you work on a species that is very distant to all species represented in the bait sequences (e.g. algae).

**Comment by KristinaGagalova** [comment] 2022-02-16 00:19
Dear Boas, 
I think I can close this ticket but I have one more question. 
Is there any reason why you classify ANS only and don't assign it as ANS/LDOX? More definition question.
Thankyou in advance

**Closed as completed** 2022-02-16 00:19 UTC

**Comment by bpucker** [comment] 2022-02-16 00:26
Dear Kristina,
Thank you. LDOX is used for the enzyme in _Arabidopsis thaliana_, but the corresponding enzyme in most other species is called ANS. Both names are usually used as synonyms. For technical reasons, it is not feasible to include a slash in the names. Do you feel that an explanatory statement would be helpful somewhere?
Best wishes,
Boas

**Comment by KristinaGagalova** [comment] 2022-02-16 00:31
Yes! It may be a naive suggestion but for someone like me just starting with flavonoids helps a lot

**Comment by bpucker** [comment] 2022-02-16 08:20
Done. I just added ANS as alternative LDOX name in the README. Thank you for the comment.
